version: '3.8'

services:
  app:
    # Nazwa obrazu, który zostanie zbudowany
    image: paragonik
    
    # Kontekst budowania (aktualny katalog) i ścieżka do Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      
    # Mapowanie portów: port_hosta:port_kontenera
    ports:
      - "3000:3000"
      
    # Przekazanie zmiennych środowiskowych z pliku .env do kontenera
    env_file:
      - .env
      
    # Zdefiniowanie woluminu do utrwalania danych bazy SQLite
    volumes:
      # Mapuje lokalny katalog 'prisma' na katalog '/app/prisma' w kontenerze
      - ./prisma:/app/prisma

# Definicja woluminów (opcjonalnie, dla lepszego zarządzania)
volumes:
  prisma_data: